modLoader="javafml" #mandatory
loaderVersion="[25,)" #mandatory
issueTrackerURL="https://github.com/BuiltBrokenModding/SBM-Bagable-Plants/issues"
displayURL="http://minecraft.curseforge.com/projects/sbm-bagable-plants"
authors="BuiltBrokenModding"

[[mods]] #mandatory
modId="baggableplants" #mandatory
version="1.0.0" #mandatory
displayName="Baggable Plants" #mandatory
description='''A simple plant capture mod''' #mandatory

[[dependencies.baggableplants]]
    modId="forge"
    mandatory=true
    versionRange="[25,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.baggableplants]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.13.2]"
    ordering="NONE"
    side="BOTH"